//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concep.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CONCEP V 3.5 - Census Allocation (SR13 06/2012  Build)")]
        public string concepMainFormText {
            get {
                return ((string)(this["concepMainFormText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2010")]
        public int assignLuduHsTypeYear {
            get {
                return ((int)(this["assignLuduHsTypeYear"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EXECUTE sp_assign_ludu_hs_type @estimates_year")]
        public string spRunAssignLuduHsType {
            get {
                return ((string)(this["spRunAssignLuduHsType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Allocate 2010 Census (SR13)\r\n\r\n")]
        public string controlGqMainButtonText {
            get {
                return ((string)(this["controlGqMainButtonText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Income Calibration")]
        public string controlVitalsMainButtonText {
            get {
                return ((string)(this["controlVitalsMainButtonText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Run")]
        public string controlVitalsRunButtonText {
            get {
                return ((string)(this["controlVitalsRunButtonText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2001,2002,2003,2004,2005,2006, 2007,2008,2009,2010")]
        public string estimatesYearComboItems {
            get {
                return ((string)(this["estimatesYearComboItems"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("182.80,191.20,197.90,205.30,212.80, 220.60,228.10,233.32,242.31,242.31")]
        public string estIncPriceIndex {
            get {
                return ((string)(this["estIncPriceIndex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PILA\\SDGINTDB;Initial Catalog=concep_test;User ID=concep_app;Password" +
            "=c0nc3p_@pp")]
        public string concepSqlConnectionString {
            get {
                return ((string)(this["concepSqlConnectionString"]));
            }
        }
    }
}
